name: Enterprise DevSecOps Gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Gate 0: Infrastructure as Code (IaC) Scanner
      - name: Trivy IaC Scan (Terraform)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './terraform'
          exit-code: '1' 
          severity: 'HIGH,CRITICAL'

      # Build the Application
      - name: Build the Docker Image
        run: docker build -t enterprise-app:latest .

      # Gate 1: GRC / Misconfiguration Scanner
      - name: Trivy Config Scan (GRC Policies)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          exit-code: '1' 
          severity: 'HIGH,CRITICAL'

      # Gate 2: Vulnerability Scanner (Software Supply Chain)
      - name: Trivy Image Scan (CVEs)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'enterprise-app:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL' 
          ignore-unfixed: true